### ISSUE TITLE
plugin expects redis on localhost 

### ISSUE THREAD

**Issue by behrtam** [PostHog/charts#36]
I upgraded the chart from 1.4.4 -> 1.4.7 which also includes a posthog upgrade from 1.20 -> 1.21. Now the plugins deployment tries to reach Redis on 127.0.0.1:
```
[MAIN] 🔴 Redis error encountered! Trying to reconnect...
 Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
```

On our dev cluster I am using redis as part of the chart (the default: redis.enabled true) which leads to the following env on the plugins pod:
```$ k exec posthog-plugins-866846fbb5-pmbsz -- env | grep REDIS
POSTHOG_REDIS_PORT=6379
POSTHOG_REDIS_HOST=posthog-posthog-redis-master
POSTHOG_REDIS_PASSWORD=**
```

I looked into the plugins repository which is using `REDIS_URL` as env var and tried setting that directly which fixed it for me.
https://github.com/PostHog/plugin-server/blob/bb8dfba4d83d068cbc497f11fcb85f0cc1ebff2d/src/config.ts#L29

```yaml
spec:
  releaseName: posthog
  chart:
    repository: "https://posthog.github.io/charts"
    name: posthog
    version: "1.4.7"
  values:
    plugins:
      resources:
      ...
      env:
        - name: REDIS_URL
          value: redis://:**@posthog-posthog-redis-master:6379/
```

Only looked very briefly and couldn't see where the REDIS env config mapping broke  ... maybe in the chart, more likely in the plugins server.
