### ISSUE TITLE
Secrets for external redis are not used unless a dummy password is set

### ISSUE THREAD

**Issue by Gibstick** [PostHog/charts#60]
As far as I can tell this will be resolved once #47 is merged, but I wanted to create this issue to get more visibility on it.

Using secrets for external redis will not work unless a dummy password is set as well.

This does not work:

```yaml
# values.yaml
redis:
  enabled: false
  host: foobar
  port: 6379
  existingSecret: redis
  existingSecretKey: password
```

This does work:

```yaml
# values.yaml
redis:
  enabled: false
  host: foobar
  port: 6379
  password: "dummy" # NOTE HERE
  existingSecret: redis
  existingSecretKey: password
```
